# Generated by Django 3.1.1 on 2020-09-17 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    """

    """
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 3, 19, 6, 539114, tzinfo=utc), verbose_name='end date'),
            preserve_default=False,
        ),
    ]
